### ISSUE TITLE
I am unable to delete some feeds

### ISSUE THREAD

**Issue by MDCore** [bearfrieze/litenin#11]
I imported my old Google Reader OPML ( :smiley: ) and have been cleaning up the feeds. I've been able to remove the ones I want except for two which stubbornly won't delete despite page reloads. I'm guessing this is a bug.

**Comment by bearfrieze** [comment]
Thanks for the bug report, I will look into it.

**Comment by StewVed** [comment]
I had the last of my feeds do this when I wanted to re-do my feed list.
It was successfully removed with the 'Clear' button :)
