### ISSUE TITLE
Design tweak suggestion

### ISSUE THREAD

**Issue by StewVed** [bearfrieze/litenin#12]
How about not setting the width of the body, and set the padding more to something like 2% ?
At least on my desktop screen, that looks better...

![original](https://cloud.githubusercontent.com/assets/12996478/8277735/8b422ca8-18bd-11e5-942a-c1f367bee72c.gif)

![better](https://cloud.githubusercontent.com/assets/12996478/8277736/907705ea-18bd-11e5-94b2-94033faa9e72.gif)

**Comment by bearfrieze** [comment]
Thanks for the suggestion and the screenshots.

On one hand, I think it would be great to use up the horizontal space available. On the other hand, I think the publication dates might get too far away from the titles, making the items harder to scan from left to right and less cohesive (especially on wide screens). I believe that was the original reason why I chose not to use up the full width on wide screens.

**Comment by StewVed** [comment]
Yes, I see.. the dates are a good way off to the right aren't they :/

Could the news story headlines be padded with a percentage from the left as well, so the headline is roughly in the center no matter the size of the screen?

I am thinking of making it look good on both HD monitors and little phone screens at the same time, unless you have some responsive layout for mobile size screens?

Regardless of layout design, this is a great project you have created :)

**Comment by StewVed** [comment]
So Sorry! I only just noticed this was still "open" and I didn't close it. Good day 😄
