### ISSUE TITLE
Is litenin down permanently?

### ISSUE THREAD

**Issue by RaoOfPhysics** [bearfrieze/litenin#14]
I haven't been able to access the site for a few months and I was wondering if you planned on continuing support.

**Comment by bearfrieze** [comment]
Thanks for asking – I haven't been especially good at communicating the status of the project. I shut down Litening a few months ago, and I don't have any plans of booting up the project again. The main reason why I stopped working on Litenin was that I stopped using it myself and lost faith in the concept.

**Comment by RaoOfPhysics** [comment]
Oh. Shame. I used it religiously when it was up. It's a really cool concept and I'm sad to see it go.
